logging:
  pattern:
    console: '%black(%d{ISO8601}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable'
  level:
    root: info
    org.zalando.logbook: trace

springdoc:
  api-docs:
    path: /api-docs

spring:
  jackson:
    time-zone: UTC
  datasource:
    url: jdbc:mysql://localhost:3306/task?connectionTimeZone=UTC
    username: test
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  elasticsearch:
    uris: http://localhost:9200
    password: pass
    username: elastic
  data:
    redis:
      database: 0
      host: localhost
      port: 6379

api:
  count:
    limit: 5
